// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cresp} from '../models';

export function CheckAndGetLatestServerVersion():Promise<cresp.Response>;

export function DoUpgrade():Promise<cresp.Response>;

export function GetDownloadUrlInfo(arg1:string):Promise<cresp.Response>;

export function RestartApplication(arg1:string):Promise<cresp.Response>;
