// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cresp} from '../models';
import {model} from '../models';

export function DeletePrompt(arg1:number):Promise<cresp.Response>;

export function GetNormalPromptList():Promise<cresp.Response>;

export function GetPromptList(arg1:number):Promise<cresp.Response>;

export function SetPromptData(arg1:model.Prompt):Promise<cresp.Response>;

export function UpdatePromptData(arg1:model.Prompt):Promise<cresp.Response>;
