// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePrompt(arg1) {
  return window['go']['prompt']['Service']['DeletePrompt'](arg1);
}

export function GetNormalPromptList() {
  return window['go']['prompt']['Service']['GetNormalPromptList']();
}

export function GetPromptList(arg1) {
  return window['go']['prompt']['Service']['GetPromptList'](arg1);
}

export function SetPromptData(arg1) {
  return window['go']['prompt']['Service']['SetPromptData'](arg1);
}

export function UpdatePromptData(arg1) {
  return window['go']['prompt']['Service']['UpdatePromptData'](arg1);
}
