// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BreakOffChatStream() {
  return window['go']['chat']['Service']['BreakOffChatStream']();
}

export function ChatCompletionStream(arg1, arg2) {
  return window['go']['chat']['Service']['ChatCompletionStream'](arg1, arg2);
}

export function CompletionStream(arg1, arg2) {
  return window['go']['chat']['Service']['CompletionStream'](arg1, arg2);
}

export function DeleteChat(arg1) {
  return window['go']['chat']['Service']['DeleteChat'](arg1);
}

export function DeleteChatCate(arg1) {
  return window['go']['chat']['Service']['DeleteChatCate'](arg1);
}

export function DeleteChatRecord(arg1) {
  return window['go']['chat']['Service']['DeleteChatRecord'](arg1);
}

export function DeleteChatRecords(arg1) {
  return window['go']['chat']['Service']['DeleteChatRecords'](arg1);
}

export function EditChat(arg1, arg2) {
  return window['go']['chat']['Service']['EditChat'](arg1, arg2);
}

export function GetAllCateList() {
  return window['go']['chat']['Service']['GetAllCateList']();
}

export function GetChatCateList(arg1) {
  return window['go']['chat']['Service']['GetChatCateList'](arg1);
}

export function GetChatList(arg1, arg2) {
  return window['go']['chat']['Service']['GetChatList'](arg1, arg2);
}

export function GetChatRecordList(arg1, arg2) {
  return window['go']['chat']['Service']['GetChatRecordList'](arg1, arg2);
}

export function GetTokensNumFromMessages(arg1, arg2) {
  return window['go']['chat']['Service']['GetTokensNumFromMessages'](arg1, arg2);
}

export function GetWsUrl() {
  return window['go']['chat']['Service']['GetWsUrl']();
}

export function MoveChatToCate(arg1, arg2) {
  return window['go']['chat']['Service']['MoveChatToCate'](arg1, arg2);
}

export function SearchChatList(arg1, arg2) {
  return window['go']['chat']['Service']['SearchChatList'](arg1, arg2);
}

export function SetChatCateData(arg1) {
  return window['go']['chat']['Service']['SetChatCateData'](arg1);
}

export function SetChatData(arg1) {
  return window['go']['chat']['Service']['SetChatData'](arg1);
}

export function SetChatRecordData(arg1) {
  return window['go']['chat']['Service']['SetChatRecordData'](arg1);
}

export function UpdateChatCateData(arg1) {
  return window['go']['chat']['Service']['UpdateChatCateData'](arg1);
}
