// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {openai} from '../models';
import {cresp} from '../models';
import {model} from '../models';

export function BreakOffChatStream():Promise<void>;

export function ChatCompletionStream(arg1:Array<openai.ChatCompletionMessage>,arg2:string):Promise<cresp.Response>;

export function CompletionStream(arg1:string,arg2:string):Promise<cresp.Response>;

export function DeleteChat(arg1:number):Promise<cresp.Response>;

export function DeleteChatCate(arg1:number):Promise<cresp.Response>;

export function DeleteChatRecord(arg1:number):Promise<cresp.Response>;

export function DeleteChatRecords(arg1:number):Promise<cresp.Response>;

export function EditChat(arg1:number,arg2:string):Promise<cresp.Response>;

export function GetAllCateList():Promise<cresp.Response>;

export function GetChatCateList(arg1:number):Promise<cresp.Response>;

export function GetChatList(arg1:number,arg2:number):Promise<cresp.Response>;

export function GetChatRecordList(arg1:number,arg2:number):Promise<cresp.Response>;

export function GetTokensNumFromMessages(arg1:model.Setting,arg2:Array<openai.ChatCompletionMessage>):Promise<cresp.Response>;

export function GetWsUrl():Promise<string>;

export function MoveChatToCate(arg1:number,arg2:number):Promise<cresp.Response>;

export function SearchChatList(arg1:string,arg2:number):Promise<cresp.Response>;

export function SetChatCateData(arg1:model.ChatCate):Promise<cresp.Response>;

export function SetChatData(arg1:model.Chat):Promise<cresp.Response>;

export function SetChatRecordData(arg1:model.ChatRecord):Promise<cresp.Response>;

export function UpdateChatCateData(arg1:model.ChatCate):Promise<cresp.Response>;
