// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {cresp} from '../models';

export function FeedBack(arg1:model.FeedBack):Promise<cresp.Response>;

export function Fullscreen():Promise<void>;

export function GeOLLamaModel(arg1:string):Promise<cresp.Response>;

export function GetFeedBackUrl(arg1:model.FeedbackReq):Promise<cresp.Response>;

export function GetGeneralInfo():Promise<cresp.Response>;

export function GetGithubReleaseList():Promise<cresp.Response>;

export function Hide():Promise<void>;

export function IsWindows():Promise<boolean>;

export function Minimise():Promise<void>;

export function NormalScreen():Promise<void>;

export function Quit():Promise<void>;

export function ReloadApp():Promise<void>;

export function SetGeneralData(arg1:model.Setting):Promise<cresp.Response>;
